version: '3'

services:
  node:
    image: node:16-alpine
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - './:/home/node/app'
    command: sh -c "npm install && npm start"